### PR TITLE
feature/gunicorn

### PR DESCRIPTION
**Pull request by Walrussuit101**
adds gunicorn to the project. 

modified the django container, the container's start command is now the gunicorn start command (see docker-compose.yml). This won't impact local development as we have a pycharm build config to start the django test server itself (what we've been using) and not the gunicorn server. In production we will just start the container and it will use the start command.

you'll have to rerun the dockerUpBackend script to update the container (this will only update changes, _it won't delete/remake_).

### CODE REVIEW

**Comment by Rithonn** [comment]
Were the documents updated with this information as well?

**Comment by Walrussuit101** [comment]
> Were the documents updated with this information as well?

Yes sir

**Review by cbrandt6 — APPROVED** [review]
Good stuff

**Review by Rithonn — APPROVED** [review]
good stuff

**Pull request merged**
